url: "https://unicatin.github.io"
baseurl: "/nagpur"


collections:
  courses:
    output: true
    permalink: /:collection/:name
  universities:
    output: true
    permalink: /:collection/:name
  colleges:
    output: true
    permalink: /:collection/:name
  schools:
    output: true
    permalink: /:collection/:name
collections_dir: collections


defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "universities"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "colleges"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "schools"
    values:
      layout: "single"
